<?php snippet('header') ?>

<div class="collection-container">
    <h1>Meine Sammlung</h1>
    
    <div class="article-bar">
        <div class="article-bar-content">
        <?php foreach (page('archiv')->children()->filterBy('status', 'listed') as $post): ?>
            <div class="article-thumbnail" data-article-id="<?= $post->id() ?>" 
                 data-title="<?= $post->title()->esc() ?>"
                 data-content="<?= $post->text()->esc() ?>"
                 data-author="<?= $post->author()->esc() ?>"
                 data-date="<?= $post->date()->toDate('d.m.Y') ?>">
                <?php if ($image = $post->image()): ?>
                <img src="<?= $image->thumb(['width' => 200])->url() ?>" 
                     alt="<?= $post->title()->esc() ?>">
                <?php endif ?>
            </div>
        <?php endforeach ?>
        </div>
    </div>

    <div class="grid-area">
        <!-- Grid zones will be generated by JavaScript -->
    </div>

    <div class="download-section">
        <button class="download-collection-btn" onclick="downloadCollection()" disabled>
            Sammlung als PDF herunterladen
        </button>
    </div>
</div>

<script src="<?= url('assets/js/jspdf.umd.min.js') ?>"></script>
<script src="<?= url('assets/js/pdf-download.js') ?>"></script>

<script>
async function downloadCollection() {
    const selectedArticles = document.querySelectorAll('.grid-area .article-thumbnail');
    if (selectedArticles.length === 0) return;
    
    // Show loading state
    const downloadBtn = document.querySelector('.download-collection-btn');
    const originalText = downloadBtn.textContent;
    downloadBtn.textContent = 'Erstelle PDF...';
    downloadBtn.disabled = true;
    
    try {
        await downloadArticles(selectedArticles);
    } catch (error) {
        console.error('PDF generation failed:', error);
        alert('PDF konnte nicht erstellt werden. Bitte versuchen Sie es erneut.');
    } finally {
        downloadBtn.textContent = originalText;
        downloadBtn.disabled = false;
    }
}
</script>

<?php snippet('footer') ?>
