<?php snippet('header') ?>

<div class="collection-container">
    <h1>Meine Sammlung</h1>
    
    <div class="article-bar">
        <div class="article-bar-content">
            <?php foreach (page('archiv')->children() as $article): ?>
            <div class="article-thumbnail" data-article-id="<?= $article->id() ?>" 
                 data-title="<?= $article->title()->esc() ?>"
                 data-content="<?= $article->text()->esc() ?>"
                 data-author="<?= $article->author()->esc() ?>"
                 data-date="<?= $article->date()->toDate('d.m.Y') ?>">
                <?php if ($image = $article->image()): ?>
                <img src="<?= $image->thumb(['width' => 200])->url() ?>" 
                     alt="<?= $article->title()->esc() ?>">
                <?php endif ?>
            </div>
            <?php endforeach ?>
        </div>
    </div>

    <div class="grid-area">
        <!-- Grid zones will be generated by JavaScript -->
    </div>

    <div class="download-section">
        <button class="download-collection-btn" onclick="downloadCollection()" disabled>
            Sammlung als PDF herunterladen
        </button>
    </div>
</div>

<script src="<?= url('assets/js/jspdf.umd.min.js') ?>"></script>
<script src="<?= url('assets/js/pdf-download.js') ?>"></script>

<script>
async function downloadCollection() {
    const selectedArticles = document.querySelectorAll('.grid-area .article-thumbnail');
    if (selectedArticles.length === 0) return;
    
    downloadArticles(selectedArticles);
}
</script>

<?php snippet('footer') ?>
